### ISSUE TITLE
Add "Base Path" to API definition

### ISSUE THREAD

**Issue by jbwiese** [u1i/yoisho#3]
Currency: Base path = /currency; resource=/get_currency *Note should verb be in resource name?
ATM: Base path = /banking/v1; resource=atm -- GET, POST only
ATM: Base path = /banking/v2; resource=atm -- Add GET ALL, Delete
Credit Card: Base path = /cardservices; resource=cards

**Comment by u1i** [comment]
looking into this

**Comment by u1i** [comment]
done for currency:
/fx/currency

The old paths / access methods will still work as well

**Comment by u1i** [comment]
done for atm

/banking/v1 and /banking/v2

**Comment by u1i** [comment]
done for credit card

/cardservices
